### ISSUE TITLE
In travatar.ini, what  these weights stands for???

### ISSUE THREAD

**Issue by sawan16** [neubig/travatar#43]
lfreq=0.0227579
fgel=0.0746014
egfl=0.0207194
egfp=0.0453778
lm=0.186005
p=-0.125645
w=0.194423
fgep=0.0365306
lmunk=0.0708743
parse=0.125179
unk=0.0978862

**Comment by philip30** [comment]
Thats the (tuned) weight parameters for the features of translation rules.

**Comment by sawan16** [comment]
Thanks for your reply. where I can get the details about each of the weight mentioned above??

**Comment by philip30** [comment]
i think they are written by rule-score.pl so you might want to take a look at the script for details. They are basically p(e|f), p(f|e), p(e), word_penalty, is_parseable(f),  back translation probability, etc. I also forget the details. Some are analogous to the Moses feature though, so you might want to check their rule feature page.
